### ISSUE TITLE
Charge Authorization Needing PIN

### ISSUE THREAD

**Issue by teghoz** [adebisi-fa/paystack-dotnet#10]
```
PayStackApi _api = new PayStackApi(CashboxSetting.Setting().PaystackSecret);
 ChargeApi chargeApi = new ChargeApi(_api);
var result = chargeApi.ChargeAuthorizationCode(card.Email, (decimal.Parse(input.Amount) * 100).ToString(), card.PaystackAuthorizationCode, null);
```
After successfully charging the authorization code
```
{
	"authorization_code": "AUTH_sqot289foa",
	"bin": "506066",
	"last4": "6666",
	"exp_month": "05",
	"exp_year": "2021",
	"channel": "card",
	"card_type": "verve DEBIT",
	"bank": "",
	"country_code": "NG",
	"brand": "verve",
	"reusable": true,
	"signature": "SIG_m8IY7AFZ85aKYyxfIKPf"
}
```

I get a "send-pin" response. Which defeats the whole idea of tokenization in the first place.  How do i fix the issue. Moreover according to the documentation there arent any PIN requirement. Am i doing something wrong?

```
curl https://api.paystack.co/transaction/charge_authorization \
-H "Authorization: Bearer SECRET_KEY" \
-H "Content-Type: application/json" \
-d '{"authorization_code": "AUTH_72btv547", "email": "customer@email.com", "amount": =}' \
-X POST
```

**Comment by adebisi-fa** [comment]
Hello @teghoz ,

Very sorry for the confusion. My bad!

The `Charge` API isn't meant to be used for charging **reusable** `AuthorizationCode`, as indicated in the code sample above.

As you rightly pointed out in your pull request #11, the `/transaction/charge_authorization` endpoint is meant for that.

A fix has been provided at this commit, [dff94da](https://github.com/adebisi-fa/paystack-dotnet/commit/dff94da738790bb1d04b566e819e980396a55600), inspired largely by your Pull Request!  Very sorry I couldn't merge your request directly, as the code needs to be updated (based on my review) before it could be merged; that, in the face of trying to make the update hit Nuget, at the earliest.

Thanks, aplenty!
