### ISSUE TITLE
ArgumentException: Accessed JArray values with invalid key value: "metadata". Int32 array index expected

### ISSUE THREAD

**Issue by ddynamight** [adebisi-fa/paystack-dotnet#15]
Hi @adebisi-fa, 

I have a bit of an issue using the list bank endpoint. 
Anytime I call it like this.
var banks = payApi.Miscellaneous.ListBanks(itemsPerPage: 50, page: 1);

OR
var banks = payApi.Miscellaneous.ListBanks(itemsPerPage: 50, page: 1).AsJObject();

OR 
var banks = payApi.Miscellaneous.ListBanks(itemsPerPage: 50, page: 1).RawJson;

OR
var banks = payApi.Miscellaneous.ListBanks(itemsPerPage: 50, page: 1).Data; 

I always get the below error

An unhandled exception occurred while processing the request.
ArgumentException: Accessed JArray values with invalid key value: "metadata". Int32 array index expected.
Newtonsoft.Json.Linq.JArray.get_Item(object key).

Kindly help look into this.
No matter what I do. Kindly help me look into this. I guess I am missing something here.

**Comment by adebisi-fa** [comment]
Hello @ddynamight ,

I'll look it up and revert, asap.

Cheers.

**Comment by ddynamight** [comment]
Hello @adebisi-fa,
So far, I have found this to affect the Transfer interface too as well 
Thank you for the reply, a quick fix will be appreciated.
Regards.

**Comment by adebisi-fa** [comment]
Thanks @ddynamight,

Kindly check if **[v0.7.5](https://github.com/adebisi-fa/paystack-dotnet/releases/tag/v0.7.5)** fix this issue.

Thanks, please.

**Comment by ddynamight** [comment]
@adebisi-fa, thanks for the fix, v0.7.5 did fixed the error, sorry to bother you again.

But I keep getting this error. When I tried using the transfer interface too.
First when I tried creating a recipient like this

`var recipentRequest = new CreateTransferRecipientRequest
               {
                    Name = disbursement.Name,
                    AccountNumber = disbursement.Account,
                    BankCode = "057",
                    Currency = "NGN",
                    Description = $"Fund Transter For {request.Reference}",
                    Type = "nuban"
               };
               var recipientResult = payApi.Transfers.Recipients.Create(recipentRequest);`

is there something I am missing here.

A quick response will be so much appreciated.
