### ISSUE TITLE
Paystack Dot Net Integration

### ISSUE THREAD

**Issue by KennedyGitHub** [adebisi-fa/paystack-dotnet#2]
Hi Adebisi,

I wish to commend your effort on Paystack integration for dot net. You have done well.

However, i am having some problems initializing the transaction object and also to be able to send the required parameters to a paystack url for payments.

Please, i would need a detailed sample code that would enable me achieve this integration.

**Comment by adebisi-fa** [comment]
Hello @KennedyGitHub,

So sorry for the delay in response. Glad to hear you love PayStack.Net.  

If it's still going to be useful, can you please post a sample of what you've tried that isn't working?  Besides, the ReadMe is a very good starting point on using the library.

Regards, please.
