### ISSUE TITLE
Could not install package 'Paystack.Net 0.7.7'

### ISSUE THREAD

**Issue by tendigitdude** [adebisi-fa/paystack-dotnet#20]
Install-Package : Could not install package 'Paystack.Net 0.7.7'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the 
package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package PayStack.Net
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

I do not want to upgrade my framework yet. What do you suggest?

**Comment by adebisi-fa** [comment]
Hello @tendigitdude ,

Trust you're good!

Since this package is targeting .Net Standard 2, I'm afraid it may not work with Net Framework less than 4.6.2. (yours is 4.5.2)

This issue #9 refers, please.

Hope this helps.


Foluso.

**Comment by tendigitdude** [comment]
Hello @adebisi-fa 

Thank you for swift response. I have upgraded the framework to 4.7.2 but sadly, the issue persist still. Please see below

Install-Package : Could not install package 'Paystack.Net 0.7.7'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7', but the package 
does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package PayStack.Net
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by tendigitdude** [comment]
> 
> 
> Hello @adebisi-fa
> 
> Thank you for swift response. I have upgraded the framework to 4.7.2 but sadly, the issue persist still. Please see below
> 
> Install-Package : Could not install package 'Paystack.Net 0.7.7'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7', but the package
> does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
> At line:1 char:1
> 
>     * Install-Package PayStack.Net
> 
>     * ```
>         + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>         + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>       ```
Hello @adebisi-fa What do you suggest we do to fix this?

**Comment by adebisi-fa** [comment]
Dear @tendigitdude,

It's really strange that you couldn't install the package even after upgrading to v4.7.2.  May I know please, the version of Visual Studio you are using?  And if possible can you check out if there is an upgrade for the Nuget package attached to your VS?

Cheers, please.

Foluso.

**Comment by tendigitdude** [comment]
Hello @adebisi-fa,

I am using VS 2015 and I am running on the latest nuget version.

Cheers.

**Comment by tendigitdude** [comment]
I opened the project using VS 2017 and was able to install the package successfully. 

Thank you.

Cheers!

**Comment by adebisi-fa** [comment]
Dear @tendigitdude ,

Glad you're able to resolve with the Visual Studio upgrade.

Sincerely appreciate your creating this issue, and willingness to make this library better. 

Cheers, please.

Foluso.
