### ISSUE TITLE
Spilt_code option

### ISSUE THREAD

**Issue by thrizy** [adebisi-fa/paystack-dotnet#21]
hi there nice library i realised there is a new parameter for split_code that has been added to initialized transactions on paystack its currently on sub account that's  active and clearly from their dashboard thats the old way

**Comment by adebisi-fa** [comment]
Resolved in [v1.0.0](https://github.com/adebisi-fa/paystack-dotnet/releases/tag/v1.0.0).  Thanks, @thrizy, and sorry that this took so long!
