### ISSUE TITLE
TransactionApi Returns False

### ISSUE THREAD

**Issue by davidasamoah** [adebisi-fa/paystack-dotnet#26]
Hello,

I'm able to consume the transaction API from Postman and my browser. However, when I try to consume the same API using this library, the status always returns false.

I checked Paystack audit log but it's not showing me anything related to API requests. I could get a clue from there.

I'm new to Paystack though.

Please any idea of what could be causing this?

Thank you.

**Comment by adebisi-fa** [comment]
> I got it working. Thanks.

I'm glad to hear you were able to fix the issue.

For the sake of those who may run into similar issue in the future, can you please post your solution here?
