### ISSUE TITLE
Apis/Transactions/Verify.cs  Authorization class missing signature property.

### ISSUE THREAD

**Issue by magoogli** [adebisi-fa/paystack-dotnet#27]
Hi,

The 'signature' Property seems to be missing in the Authorization class unless I am mistaken? If you have a look at https://paystack.com/docs/payments/recurring-charges/ under the 'Get the Card authorization' heading it appears 'signature' should be present in this class, but it is not.

![image](https://github.com/user-attachments/assets/679d8952-af47-4449-9790-a468247e9b15)

**Comment by Victor-Ndulue** [comment]
@magoogli the signature property rightly exists in the Authorization class.

The response in quote is the payment verification by Paystack. 
You can find it on the SDK via TransactionResponseModel=>Data=> Authorization. Also check attached image for confirmation.

If that clears your doubt, you can kindly close the issue. 
![Screenshot 2024-11-13 101543](https://github.com/user-attachments/assets/06016494-f318-484c-bed3-44bcffe55655)
