### ISSUE TITLE
Payment gateway integration in MVC 6.0

### ISSUE THREAD

**Issue by MaheshNeelam** [adebisi-fa/paystack-dotnet#3]
Hi am trying to implement payment gateway in my web solution when i am tried with the sample solution am getting an error 
and can you please help me step by process how to call the process to a controller and all in my sloution or else any demo session 
![image](https://user-images.githubusercontent.com/29422341/27119914-55385836-50ff-11e7-8cd2-9c9ba4e5531c.png)

**Comment by adebisi-fa** [comment]
Hello @MaheshNeelam ,

Building the code or the sample project requires Visual Studio 2017, as it makes use of some C# 6/7 constructs.

Hope it helps.
