### ISSUE TITLE
Charge a Card

### ISSUE THREAD

**Issue by Akinnagbe** [adebisi-fa/paystack-dotnet#5]
Hello, 

Please I need to charge a card from a mobile app (Xamarin Forms) but can't find any class from your nugget package to do that. Also I have tried using the Paystack android sdk but not compatible with Xamarin.

Thanks

**Comment by adebisi-fa** [comment]
Hello @Akinnagbe,

The Card API, coincidentally happens to be one of the few APIs yet to be implemented.  I'll roll it in and push an update, as soon as possible, since you've voted it up!

Hope this helps.

Regards, please.

**Comment by adebisi-fa** [comment]
This feature has been implemented in this [commit 8226c6e7](https://github.com/adebisi-fa/paystack-dotnet/commit/8226c6e7ad27b96c2ac8654ec05b5c4e5196cbf2) and is now available on Nuget as v0.7.1

**Comment by DemiladeA** [comment]
@Akinnagbe Hi I think we are trying to achieve the same thing charge cards with this api on a Xamarin forms application, do you mind sharing your code & environment settings, I have tried but I am unable to add the package to my Xamarin forms application
