### ISSUE TITLE
Paystack API not working for .Net Framework

### ISSUE THREAD

**Issue by iensteins2k** [adebisi-fa/paystack-dotnet#6]
Good afternoon, I'm trying to integrate Paystack API to my app built with .Net Framework 4.5.2 but it isn't installing.  I get the following Error: **Could not install package 'Paystack.Net 0.7.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.**		

Further study shows that it only supports .Net Core. Is there a package for my Framework if not could you please redirect me to resources that helps me. 

Thanks

**Comment by adebisi-fa** [comment]
Hi @iensteins2k ,

Hope you're good!

PayStack.Net supports **.Net Standard 2.0**. As such, it can only work with **.Net Framework v4.6.1** and later.  

If there isn't any tight requirement on your supporting .Net Framework 4.5.1, I will suggest you update your project/solution to target 4.6.1 to use this library.  Besides, .Net Framework 4.6.1 is **very stable**, too!

Hope this helps.

Please check .Net Stardard 2.0 supported platforms [here](https://github.com/dotnet/standard/blob/master/docs/versions.md).
